env:
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 9
  files: ['*.ts', '*.test.ts']
  project: ['./tsconfig.json']
plugins:
  - '@typescript-eslint'
