# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: white-elephant-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: baronwilleford
      POSTGRES_PASSWORD: hard_water_client_mixture_moon_solver
      POSTGRES_DB: elehpant-base

  redis:
    image: 'redis:alpine'

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - '6379:6379'

    volumes:
      - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
